/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capaPresentacion;

import capaLogica.*;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/**
 *
 * @author pinedas
 */
public class InterfazReparaciones extends javax.swing.JFrame implements Observer {

    private Gestor gestor;
    private DefaultListModel<String> modeloListaVehiculos;
    private DefaultListModel<String> modeloListaOperarios;
    private DefaultListModel<String> modeloListaPiezas;
    private DefaultListModel<String> modeloListaSalas;
    private DefaultComboBoxModel<String> modeloCBTareas;
    private DefaultComboBoxModel<String> modeloCBVehiculos;
    private DefaultComboBoxModel<String> modeloCBReparaciones;
    private DefaultComboBoxModel<String> modelosCBsalas;

    /**
     * Creates new form InterfazReparaciones
     */
    public InterfazReparaciones() {
        initComponents();

        iniciarComponentesPropios();
    }

    private void iniciarComponentesPropios() {
        gestor = new Gestor();
        modeloListaVehiculos = new DefaultListModel();
        modeloListaOperarios = new DefaultListModel();
        modeloListaPiezas = new DefaultListModel<String>();
        modeloListaSalas = new DefaultListModel<String>();
        modeloCBVehiculos = new DefaultComboBoxModel<String>();
        modeloCBTareas = new DefaultComboBoxModel<String>();
        modeloCBReparaciones = new DefaultComboBoxModel<String>();
        modelosCBsalas = new DefaultComboBoxModel<String>();

        this.jlVehiculos.setModel(modeloListaVehiculos);
        this.jlOperarios.setModel(modeloListaOperarios);
        this.jlPieza.setModel(modeloListaPiezas);
        this.jlListaSalas.setModel(modelosCBsalas);
        this.jcbTareasPieza.setModel(modeloCBTareas);
        this.jcbVehiculoReparacion.setModel(modeloCBVehiculos);
        this.jcbTareaReparacion.setModel(modeloCBReparaciones);
        this.jcbTareaSala.setModel(modelosCBsalas);

        gestor.addObserver(this);

        this.actualizarVistaLista(modeloListaVehiculos, gestor.obtenerListaVehiculos());
        this.actualizarVistaLista(modeloListaOperarios, gestor.obtenerListaOperarios());
        this.actualizarVistaLista(modeloListaPiezas, gestor.obtenerListaPiezas());
        this.actualizarVistaLista(modeloListaSalas, gestor.obtenerListaSalas());
        this.actualizarVistaCB(modeloCBVehiculos, gestor.obtenerListaVehiculos());
        this.actualizarVistaCB(modeloCBTareas, gestor.obtenerNombresListaTareas());
        this.actualizarVistaCB(modeloCBReparaciones, gestor.obtenerNombresListaReparaciones());
        this.actualizarVistaCB(modelosCBsalas, gestor.obtenerNombresListaSalasDeReparacion());

        this.setJlStatus("");
    }

    public void actualizarVistaLista(DefaultListModel modelo, String[] lista) {
        modelo.clear();
        for (String linea : lista) {
            modelo.addElement(linea);
        }
    }

    public void actualizarVistaCB(DefaultComboBoxModel modelo, String[] lista) {
        modelo.removeAllElements();
        for (String linea : lista) {
            modelo.addElement(linea);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbCrearVehiculo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlVehiculos = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfPlaca = new javax.swing.JTextField();
        jtfModelo = new javax.swing.JTextField();
        jtfNombreProp = new javax.swing.JTextField();
        jtfApellidoProp = new javax.swing.JTextField();
        jtfEstadoVehi = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jsAniosOp = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jtfNombreOperario = new javax.swing.JTextField();
        jtfApellidoOperario = new javax.swing.JTextField();
        jtfDireccionOp = new javax.swing.JTextField();
        jtfCargoOp = new javax.swing.JTextField();
        jtfTelefonoOp = new javax.swing.JFormattedTextField();
        jtfIDOperario = new javax.swing.JFormattedTextField();
        jbCrearOp = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jlOperarios = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        jtfCodigoPieza = new javax.swing.JTextField();
        jtfMarcaPieza = new javax.swing.JTextField();
        jtfPaisPieza = new javax.swing.JTextField();
        jtfDescripcionPieza = new javax.swing.JTextField();
        jtfCantidadPieza = new javax.swing.JTextField();
        jtfProblemaPieza = new javax.swing.JTextField();
        jlCodigoPieza = new javax.swing.JLabel();
        jlMarcaPieza = new javax.swing.JLabel();
        jlPaisPieza = new javax.swing.JLabel();
        jlDesPieza = new javax.swing.JLabel();
        jlCanPieza = new javax.swing.JLabel();
        jlProbPieza = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlPieza = new javax.swing.JList();
        jbCrearPieza = new javax.swing.JButton();
        jlIdTarea = new javax.swing.JLabel();
        jcbTareasPieza = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jlTareaNombre = new javax.swing.JLabel();
        jlTareaDescripcion = new javax.swing.JLabel();
        jlTareaFechaCreacion = new javax.swing.JLabel();
        lbTareaDuracionPropuesta = new javax.swing.JLabel();
        jlTareaDuracionReal = new javax.swing.JLabel();
        jlReparacion = new javax.swing.JLabel();
        jtfTareNombre = new javax.swing.JTextField();
        jtfTareaDescripcion = new javax.swing.JTextField();
        jtfTareaFechaCreacion = new javax.swing.JFormattedTextField();
        jtfTareaDuracionPropuesta = new javax.swing.JFormattedTextField();
        jtfTareaDuracionReal = new javax.swing.JFormattedTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jlTareas = new javax.swing.JList();
        jbCrearTarea = new javax.swing.JButton();
        jcbTareaReparacion = new javax.swing.JComboBox();
        jlTarea = new javax.swing.JLabel();
        jcbTareaSala = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jcbVehiculoReparacion = new javax.swing.JComboBox();
        jtfFechaReparacion = new javax.swing.JFormattedTextField();
        jtfNombreReparacion = new javax.swing.JTextField();
        jtfCodigoReparacion = new javax.swing.JTextField();
        jsp = new javax.swing.JScrollPane();
        jlListaReparaciones = new javax.swing.JList();
        jbCrearReparacion = new javax.swing.JButton();
        jlStatus = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jtfDescripcionSala = new javax.swing.JTextField();
        jtfUbicacionSala = new javax.swing.JTextField();
        jsCapacidadSala = new javax.swing.JSpinner();
        jScrollPane5 = new javax.swing.JScrollPane();
        jlListaSalas = new javax.swing.JList();
        jbCrearSala = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Vehiculo"));

        jbCrearVehiculo.setText("Crear");
        jbCrearVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCrearVehiculoActionPerformed(evt);
            }
        });

        jlVehiculos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jlVehiculos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(jlVehiculos);

        jLabel1.setText("Placa:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Modelo");

        jLabel4.setText("Apellido:");

        jLabel5.setText("Estado:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jbCrearVehiculo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel1))
                            .addGap(8, 8, 8)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtfModelo)
                                .addComponent(jtfPlaca)
                                .addComponent(jtfNombreProp, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfApellidoProp, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                    .addComponent(jtfEstadoVehi))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfNombreProp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfApellidoProp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfEstadoVehi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbCrearVehiculo))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Operario"));

        jLabel6.setText("Nombre:");

        jLabel7.setText("Apellido:");

        jLabel8.setText("ID:");

        jLabel9.setText("Direccion:");

        jLabel10.setText("Teléfono:");

        jLabel11.setText("Cargo:");

        jsAniosOp.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        jLabel12.setText("Exp");

        try {
            jtfTelefonoOp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jtfIDOperario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jbCrearOp.setText("Crear");
        jbCrearOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCrearOpActionPerformed(evt);
            }
        });

        jlOperarios.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jlOperarios);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jbCrearOp)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jtfNombreOperario, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jtfApellidoOperario))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfDireccionOp)
                            .addComponent(jtfTelefonoOp)
                            .addComponent(jtfIDOperario)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfCargoOp)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jsAniosOp, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfNombreOperario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtfApellidoOperario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtfIDOperario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtfDireccionOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtfTelefonoOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtfCargoOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jsAniosOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCrearOp))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Pieza"));

        jtfCodigoPieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodigoPiezaActionPerformed(evt);
            }
        });

        jlCodigoPieza.setText("Codigo:");

        jlMarcaPieza.setText("Marca:");

        jlPaisPieza.setText("País:");

        jlDesPieza.setText("Descripción:");

        jlCanPieza.setText("Cantidad:");

        jlProbPieza.setText("Problema:");

        jlPieza.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jlPieza);

        jbCrearPieza.setText("Crear");
        jbCrearPieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCrearPiezaActionPerformed(evt);
            }
        });

        jlIdTarea.setText("Tarea:");

        jcbTareasPieza.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCodigoPieza)
                            .addComponent(jlMarcaPieza)
                            .addComponent(jlPaisPieza)
                            .addComponent(jlDesPieza)
                            .addComponent(jlCanPieza)
                            .addComponent(jlProbPieza)
                            .addComponent(jbCrearPieza)
                            .addComponent(jlIdTarea))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfCodigoPieza, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(jtfMarcaPieza)
                            .addComponent(jtfPaisPieza)
                            .addComponent(jtfDescripcionPieza)
                            .addComponent(jtfCantidadPieza)
                            .addComponent(jtfProblemaPieza)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jcbTareasPieza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCodigoPieza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCodigoPieza))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfMarcaPieza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlMarcaPieza))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPaisPieza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPaisPieza))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDescripcionPieza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlDesPieza))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCantidadPieza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCanPieza))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfProblemaPieza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlProbPieza))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlIdTarea)
                    .addComponent(jcbTareasPieza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbCrearPieza))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Tarea"));

        jlTareaNombre.setText("Nombre:");

        jlTareaDescripcion.setText("Descripción:");

        jlTareaFechaCreacion.setText("Creación:");

        lbTareaDuracionPropuesta.setText("Propuesta:");

        jlTareaDuracionReal.setText("Real:");

        jlReparacion.setText("Reparacion:");

        jtfTareaFechaCreacion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/mm/yyyy"))));
        jtfTareaFechaCreacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfTareaFechaCreacionKeyTyped(evt);
            }
        });

        jtfTareaDuracionPropuesta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        jtfTareaDuracionReal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jtfTareaDuracionReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTareaDuracionRealActionPerformed(evt);
            }
        });

        jlTareas.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jlTareas);

        jbCrearTarea.setText("Crear");
        jbCrearTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCrearTareaActionPerformed(evt);
            }
        });

        jcbTareaReparacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jlTarea.setText("Tarea:");

        jcbTareaSala.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlTareaDescripcion)
                            .addComponent(jlTareaFechaCreacion)
                            .addComponent(jlTareaNombre))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfTareaFechaCreacion)
                            .addComponent(jtfTareaDescripcion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfTareNombre, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jScrollPane4)
                    .addComponent(jbCrearTarea)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTareaDuracionPropuesta)
                            .addComponent(jlTareaDuracionReal)
                            .addComponent(jlReparacion)
                            .addComponent(jlTarea))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfTareaDuracionPropuesta, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfTareaDuracionReal, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jcbTareaReparacion, 0, 85, Short.MAX_VALUE)
                            .addComponent(jcbTareaSala, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTareaNombre)
                    .addComponent(jtfTareNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTareaDescripcion)
                    .addComponent(jtfTareaDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTareaFechaCreacion)
                    .addComponent(jtfTareaFechaCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTareaDuracionPropuesta)
                    .addComponent(jtfTareaDuracionPropuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTareaDuracionReal)
                    .addComponent(jtfTareaDuracionReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlReparacion)
                    .addComponent(jcbTareaReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTarea)
                    .addComponent(jcbTareaSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbCrearTarea))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Reparacion"));

        jLabel13.setText("Codigo:");

        jLabel14.setText("Nombre:");

        jLabel15.setText("Fecha:");

        jLabel16.setText("Vehiculo:");

        jcbVehiculoReparacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jtfFechaReparacion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        jtfNombreReparacion.setText("jTextField1");

        jtfCodigoReparacion.setText("jTextField2");

        jlListaReparaciones.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jsp.setViewportView(jlListaReparaciones);

        jbCrearReparacion.setText("Crear");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jsp)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbVehiculoReparacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfFechaReparacion)
                            .addComponent(jtfNombreReparacion, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(jtfCodigoReparacion)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jbCrearReparacion)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jtfCodigoReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jtfNombreReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jtfFechaReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jcbVehiculoReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jsp, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbCrearReparacion))
        );

        jlStatus.setText("jLabel6");

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Sala de Reparacion"));

        jLabel17.setText("Descripcion:");

        jLabel19.setText("Ubicacion:");

        jLabel20.setText("Capacidad:");

        jtfDescripcionSala.setText("jTextField1");

        jtfUbicacionSala.setText("jTextField2");

        jsCapacidadSala.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        jlListaSalas.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jlListaSalas);

        jbCrearSala.setText("Crear");
        jbCrearSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCrearSalaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfDescripcionSala))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(13, 13, 13)
                        .addComponent(jtfUbicacionSala))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(jsCapacidadSala, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbCrearSala))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jtfDescripcionSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jtfUbicacionSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jsCapacidadSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jbCrearSala))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlStatus)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jlStatus)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCrearVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCrearVehiculoActionPerformed

        String placa = this.jtfPlaca.getText();
        String modelo = this.jtfModelo.getText();
        String nombreProp = this.jtfNombreProp.getText();
        String apellidoProp = this.jtfApellidoProp.getText();
        String estado = this.jtfEstadoVehi.getText();

        gestor.agregarVehiculo(placa, modelo, nombreProp, apellidoProp, estado);
        this.actualizarVistaLista(modeloListaVehiculos, gestor.obtenerListaVehiculos());

    }//GEN-LAST:event_jbCrearVehiculoActionPerformed

    private void jbCrearOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCrearOpActionPerformed
        String cedula = this.jtfIDOperario.getText();
        String nombre = this.jtfNombreOperario.getText();
        String apellido = this.jtfApellidoOperario.getText();
        String telefono = this.jtfTelefonoOp.getText();
        String direccion = this.jtfDireccionOp.getText();
        int anios = (int) this.jsAniosOp.getValue();
        String cargo = this.jtfCargoOp.getText();

        gestor.agregarOperario(cedula, nombre, apellido, telefono, direccion, anios, cargo);
        this.actualizarVistaLista(modeloListaOperarios, gestor.obtenerListaOperarios());
    }//GEN-LAST:event_jbCrearOpActionPerformed

    private void jtfCodigoPiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodigoPiezaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodigoPiezaActionPerformed

    private void jbCrearPiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCrearPiezaActionPerformed

        String codigoPieza = this.jtfCodigoPieza.getText();
        String marcaPieza = this.jtfMarcaPieza.getText();
        String paisPieza = this.jtfPaisPieza.getText();
        String descripcionPieza = this.jtfDescripcionPieza.getText();
        int cantidadPieza = Integer.parseInt(this.jtfCantidadPieza.getText());
        String problemaPieza = this.jtfProblemaPieza.getText();
        String nombreTareaPieza = (String) this.jcbTareasPieza.getSelectedItem();
        gestor.AgregarPieza(codigoPieza, marcaPieza, paisPieza,
                descripcionPieza, cantidadPieza, problemaPieza, nombreTareaPieza);
        this.actualizarVistaLista(modeloListaPiezas, gestor.obtenerListaPiezas());
        this.actualizarVistaCB(modeloCBTareas, gestor.obtenerNombresListaTareas());


    }//GEN-LAST:event_jbCrearPiezaActionPerformed

    private void jtfTareaDuracionRealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTareaDuracionRealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTareaDuracionRealActionPerformed

    private void jtfTareaFechaCreacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTareaFechaCreacionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTareaFechaCreacionKeyTyped

    private void jbCrearTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCrearTareaActionPerformed

        try {
            SimpleDateFormat formatter = new SimpleDateFormat("dd/mm/yyyy");
            String nombreTarea = this.jtfTareNombre.getText();
            String descripcionTarea = this.jtfTareaDescripcion.getText();
            Date fechaCreacionTarea = (Date) formatter.parse(this.jtfTareaFechaCreacion.getText());
            int duracionRealTarea = Integer.parseInt(this.jtfTareaDuracionReal.getText());
            int duracionPropuestaTarea = Integer.parseInt(this.jtfTareaDuracionPropuesta.getText());
            String codigoReparacion = (String) this.jcbTareaReparacion.getSelectedItem();
            

//                            rs.getString("nombreTarea"),
//                    rs.getString("descripcionTarea"),
//                    rs.getDate("fechaCreacionTarea"),
//                    rs.getInt("duracionRealTarea"),
//                    rs.getInt("duracionPropuestaTarea"),
//                    rs.getString("codigo_reparacion"),
//                    rs.getInt("id_sala")
        } catch (ParseException ex) {
            Logger.getLogger(InterfazReparaciones.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jbCrearTareaActionPerformed

    private void jbCrearSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCrearSalaActionPerformed
        String descripcion = this.jtfDescripcionSala.getText();
        String ubicacion = this.jtfUbicacionSala.getText();
        int capacidad = (int)this.jsCapacidadSala.getValue();
        
        gestor.agregarSala(descripcion, ubicacion, capacidad);
        this.actualizarVistaLista(modeloListaSalas, gestor.obtenerListaSalas());
    }//GEN-LAST:event_jbCrearSalaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazReparaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazReparaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazReparaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazReparaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazReparaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton jbCrearOp;
    private javax.swing.JButton jbCrearPieza;
    private javax.swing.JButton jbCrearReparacion;
    private javax.swing.JButton jbCrearSala;
    private javax.swing.JButton jbCrearTarea;
    private javax.swing.JButton jbCrearVehiculo;
    private javax.swing.JComboBox jcbTareaReparacion;
    private javax.swing.JComboBox jcbTareaSala;
    private javax.swing.JComboBox jcbTareasPieza;
    private javax.swing.JComboBox jcbVehiculoReparacion;
    private javax.swing.JLabel jlCanPieza;
    private javax.swing.JLabel jlCodigoPieza;
    private javax.swing.JLabel jlDesPieza;
    private javax.swing.JLabel jlIdTarea;
    private javax.swing.JList jlListaReparaciones;
    private javax.swing.JList jlListaSalas;
    private javax.swing.JLabel jlMarcaPieza;
    private javax.swing.JList jlOperarios;
    private javax.swing.JLabel jlPaisPieza;
    private javax.swing.JList jlPieza;
    private javax.swing.JLabel jlProbPieza;
    private javax.swing.JLabel jlReparacion;
    private javax.swing.JLabel jlStatus;
    private javax.swing.JLabel jlTarea;
    private javax.swing.JLabel jlTareaDescripcion;
    private javax.swing.JLabel jlTareaDuracionReal;
    private javax.swing.JLabel jlTareaFechaCreacion;
    private javax.swing.JLabel jlTareaNombre;
    private javax.swing.JList jlTareas;
    private javax.swing.JList jlVehiculos;
    private javax.swing.JSpinner jsAniosOp;
    private javax.swing.JSpinner jsCapacidadSala;
    private javax.swing.JScrollPane jsp;
    private javax.swing.JTextField jtfApellidoOperario;
    private javax.swing.JTextField jtfApellidoProp;
    private javax.swing.JTextField jtfCantidadPieza;
    private javax.swing.JTextField jtfCargoOp;
    private javax.swing.JTextField jtfCodigoPieza;
    private javax.swing.JTextField jtfCodigoReparacion;
    private javax.swing.JTextField jtfDescripcionPieza;
    private javax.swing.JTextField jtfDescripcionSala;
    private javax.swing.JTextField jtfDireccionOp;
    private javax.swing.JTextField jtfEstadoVehi;
    private javax.swing.JFormattedTextField jtfFechaReparacion;
    private javax.swing.JFormattedTextField jtfIDOperario;
    private javax.swing.JTextField jtfMarcaPieza;
    private javax.swing.JTextField jtfModelo;
    private javax.swing.JTextField jtfNombreOperario;
    private javax.swing.JTextField jtfNombreProp;
    private javax.swing.JTextField jtfNombreReparacion;
    private javax.swing.JTextField jtfPaisPieza;
    private javax.swing.JTextField jtfPlaca;
    private javax.swing.JTextField jtfProblemaPieza;
    private javax.swing.JTextField jtfTareNombre;
    private javax.swing.JTextField jtfTareaDescripcion;
    private javax.swing.JFormattedTextField jtfTareaDuracionPropuesta;
    private javax.swing.JFormattedTextField jtfTareaDuracionReal;
    private javax.swing.JFormattedTextField jtfTareaFechaCreacion;
    private javax.swing.JFormattedTextField jtfTelefonoOp;
    private javax.swing.JTextField jtfUbicacionSala;
    private javax.swing.JLabel lbTareaDuracionPropuesta;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jlStatus
     */
    public String getJlStatus() {
        return jlStatus.getText();
    }

    /**
     * @param mensaje
     */
    public void setJlStatus(String mensaje) {
        this.jlStatus.setText(mensaje);
    }

    @Override
    public void update(Observable o, Object arg) {
        this.setJlStatus((String) arg);
    }
}
